-- MySQL Script generated by MySQL Workbench
-- Thu 25 Jul 2019 11:02:51 PM AST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JContactsManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JContactsManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JContactsManager` DEFAULT CHARACTER SET utf8 ;
USE `JContactsManager` ;

-- -----------------------------------------------------
-- Table `JContactsManager`.`Company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Company` (
  `companyId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`companyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Note` (
  `noteId` INT NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`noteId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`Photo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Photo` (
  `photoId` INT NOT NULL,
  `path` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`photoId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`Position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Position` (
  `positionId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`positionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`User` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `createDate` DATE NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`Contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Contact` (
  `contactId` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(20) NOT NULL,
  `lastName` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `companyId` INT NULL,
  `noteId` INT NULL,
  `photoId` INT NULL,
  `positionId` INT NULL,
  `userEmail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`contactId`),
  INDEX `fk_Contact_Company1_idx` (`companyId` ASC),
  INDEX `fk_Contact_Note1_idx` (`noteId` ASC),
  INDEX `fk_Contact_Photo1_idx` (`photoId` ASC),
  INDEX `fk_Contact_Posicion1_idx` (`positionId` ASC),
  INDEX `fk_Contact_User1_idx` (`userEmail` ASC),
  CONSTRAINT `fk_Contacto_Empresa1`
    FOREIGN KEY (`companyId`)
    REFERENCES `JContactsManager`.`Company` (`companyId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_Note1`
    FOREIGN KEY (`noteId`)
    REFERENCES `JContactsManager`.`Note` (`noteId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_Photo1`
    FOREIGN KEY (`photoId`)
    REFERENCES `JContactsManager`.`Photo` (`photoId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_Posicion1`
    FOREIGN KEY (`positionId`)
    REFERENCES `JContactsManager`.`Position` (`positionId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contact_User1`
    FOREIGN KEY (`userEmail`)
    REFERENCES `JContactsManager`.`User` (`email`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JContactsManager`.`Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JContactsManager`.`Phone` (
  `phone` VARCHAR(45) NOT NULL DEFAULT '',
  `idContact` INT NOT NULL,
  `phoneType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`phone`, `idContact`),
  INDEX `fk_Phone_Contact_idx` (`idContact` ASC),
  CONSTRAINT `fk_Telefono_Contacto`
    FOREIGN KEY (`idContact`)
    REFERENCES `JContactsManager`.`Contact` (`contactId`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
